import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

// Load .env file from the root directory
const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, '../.env') });

const SUPA_URL = process.env.VITE_SUPABASE_URL;
const SUPA_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY;
const BREVO_KEY = process.env.VITE_BREVO_API_KEY;
const SENDER_EMAIL = process.env.VITE_BREVO_SENDER_EMAIL || 'vitabsquare@gmail.com';
const ADMIN_EMAILS = (process.env.VITE_ADMIN_EMAILS || 'vitabsquare@gmail.com').split(',').map(e => e.trim());

async function run() {
  console.log(`[Daily Report] Starting daily report generation...`);

  // Calculate Yesterday's bounds
  const now = new Date();
  const yesterday = new Date(now);
  yesterday.setDate(yesterday.getDate() - 1);
  yesterday.setHours(0, 0, 0, 0); // Start of yesterday
  
  const endOfYesterday = new Date(yesterday);
  endOfYesterday.setHours(23, 59, 59, 999); // End of yesterday

  const startTimeStr = yesterday.toISOString();
  const endTimeStr = endOfYesterday.toISOString();

  console.log(`[Daily Report] Fetching data for: ${startTimeStr} to ${endTimeStr}`);

  // Fetch Data from Supabase
  const headers = {
    'apikey': SUPA_KEY,
    'Authorization': `Bearer ${SUPA_KEY}`,
    'Content-Type': 'application/json'
  };

  const fetchTable = async (table, dateCol) => {
    const url = `${SUPA_URL}/rest/v1/${table}?${dateCol}=gte.${startTimeStr}&${dateCol}=lte.${endTimeStr}&order=${dateCol}.asc`;
    const res = await fetch(url, { headers });
    if (!res.ok) throw new Error(`Failed to fetch ${table}: ${await res.text()}`);
    return res.json();
  };

  try {
    const [sessions, pageViews, events] = await Promise.all([
      fetchTable('visitor_sessions', 'started_at'),
      fetchTable('page_views', 'entered_at'),
      fetchTable('analytics_events', 'created_at')
    ]);

    console.log(`[Daily Report] Found ${sessions.length} sessions, ${pageViews.length} page views, ${events.length} events.`);

    if (sessions.length === 0) {
      console.log(`[Daily Report] No sessions yesterday. Sending 'empty' email.`);
      await sendEmail("No visitors yesterday.", [], yesterday);
      return;
    }

    // Build CSV
    const rows = [];
    // Header
    rows.push(['Session Time', 'Location', 'Device', 'Browser', 'Source', 'Duration (s)', 'Total Pages', 'Key Interactions']);

    for (const session of sessions) {
      const sessEvents = events.filter(e => e.session_id === session.session_id);
      const sessPages = pageViews.filter(p => p.session_id === session.session_id);
      
      const timeStr = new Date(session.started_at).toLocaleString('en-US', { timeZone: 'Asia/Kolkata' });
      const location = [session.city, session.country].filter(Boolean).join(', ') || 'Unknown';
      
      // Summarize interactions
      const interactions = sessEvents.map(e => {
        if (e.event_name === 'scroll_depth') return `Scrolled ${e.event_data.percent}%`;
        if (e.event_name === 'section_enter') return `Entered ${e.event_data.section}`;
        if (e.event_name === 'section_exit') return `Viewed ${e.event_data.section} (${e.event_data.seconds_spent}s)`;
        if (e.event_name === 'click') return `Clicked: ${e.event_data.element}`;
        return e.event_name;
      });
      
      // Escape CSV cells
      const escape = (str) => `"${String(str).replace(/"/g, '""')}"`;

      rows.push([
        timeStr,
        location,
        session.device_type || 'Unknown',
        session.browser || 'Unknown',
        session.traffic_source || 'Unknown',
        session.duration_seconds || 0,
        sessPages.length,
        interactions.join(' | ') // Join interactions with pipe for readability in CSV
      ].map(escape).join(','));
    }

    const csvContent = rows.join('\n');
    console.log(`[Daily Report] CSV generated successfully.`);

    // Send via Brevo
    await sendEmail("Please find the attached daily visitor report.", csvContent, yesterday);
    console.log(`[Daily Report] Done!`);

  } catch (err) {
    console.error(`[Daily Report] Fatal Error:`, err);
    process.exit(1);
  }
}

async function sendEmail(message, csvContent, reportDate) {
  const dateStr = reportDate.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
  const subject = `Daily Visitor Report: ${dateStr}`;

  const payload = {
    sender: { name: process.env.VITE_BREVO_SENDER_NAME || 'VTAB Square', email: SENDER_EMAIL },
    to: ADMIN_EMAILS.map(email => ({ email })),
    subject: subject,
    htmlContent: `
      <h2>Daily Visitor Report</h2>
      <p>Report for: <strong>${dateStr}</strong></p>
      <p>${message}</p>
      <p><br>Automated Report generated by VTAB Square System.</p>
    `,
  };

  if (csvContent && csvContent.length > 0) {
    const base64Content = Buffer.from(csvContent).toString('base64');
    payload.attachment = [
      {
        content: base64Content,
        name: `visitor_report_${reportDate.toISOString().split('T')[0]}.csv`
      }
    ];
  }

  const res = await fetch('https://api.brevo.com/v3/smtp/email', {
    method: 'POST',
    headers: {
      'api-key': BREVO_KEY,
      'Content-Type': 'application/json',
      'Accept': 'application/json'
    },
    body: JSON.stringify(payload)
  });

  if (!res.ok) {
    const txt = await res.text();
    throw new Error(`Brevo API Error: ${res.status} ${txt}`);
  }

  console.log(`[Daily Report] Email successfully sent to admins via Brevo!`);
}

run();
