import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import dotenv from 'dotenv';
dotenv.config();
const execFileAsync=promisify(execFile);
const tenant=process.env.MS_GRAPH_TENANT_ID, client=process.env.MS_GRAPH_CLIENT_ID, secret=process.env.MS_GRAPH_CLIENT_SECRET;
const sender=process.env.VISITOR_REPORT_SENDER || 'Contactsales@vtabsquare.com';
const recipients=(process.env.VISITOR_REPORT_TO || 'Information@vtabsquare.com,vitabsquare@gmail.com').split(',').map(x=>x.trim()).filter(Boolean);
if(!tenant||!client||!secret) throw new Error('Missing MS_GRAPH_TENANT_ID, MS_GRAPH_CLIENT_ID or MS_GRAPH_CLIENT_SECRET');
const {stdout}=await execFileAsync(process.execPath,['scripts/nginxVisitorReport.js'],{env:{...process.env,REPORT_DAYS:process.env.REPORT_DAYS||'1'}});
const report=JSON.parse(stdout);
const rows=(report.conversions||[]).map(([k,v])=>`<li>${k}: <strong>${v}</strong></li>`).join('')||'<li>No tracked CTA conversions yet</li>';
const pages=(report.top_pages||[]).slice(0,8).map(([k,v])=>`<li>${k}: ${v}</li>`).join('');
const html=`<h2>VTAB Square Daily Visitor Intelligence</h2><p><strong>Likely human page requests:</strong> ${report.likely_human_page_requests}<br><strong>Bot requests:</strong> ${report.bot_requests}<br><strong>Scanner requests:</strong> ${report.scanner_requests}<br><strong>Service-interest requests:</strong> ${report.service_interest_requests}<br><strong>Contact page requests:</strong> ${report.contact_page_requests}<br><strong>Tracked CTA actions:</strong> ${report.conversion_actions}</p><h3>Conversions</h3><ul>${rows}</ul><h3>Top pages</h3><ul>${pages}</ul><p><strong>Suggested next action:</strong> ${report.next_action}</p><p style="color:#666">Aggregate operational analytics only. No raw IP addresses are included.</p>`;
const tokenRes=await fetch(`https://login.microsoftonline.com/${tenant}/oauth2/v2.0/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:client,client_secret:secret,scope:'https://graph.microsoft.com/.default',grant_type:'client_credentials'})});
if(!tokenRes.ok) throw new Error(`Graph token failed: ${tokenRes.status} ${await tokenRes.text()}`);
const {access_token}=await tokenRes.json();
const sendRes=await fetch(`https://graph.microsoft.com/v1.0/users/${encodeURIComponent(sender)}/sendMail`,{method:'POST',headers:{Authorization:`Bearer ${access_token}`,'Content-Type':'application/json'},body:JSON.stringify({message:{subject:`VTAB Square Daily Visitor Intelligence - ${new Date().toLocaleDateString('en-IN')}`,body:{contentType:'HTML',content:html},toRecipients:recipients.map(address=>({emailAddress:{address}}))},saveToSentItems:true})});
if(!sendRes.ok) throw new Error(`Graph sendMail failed: ${sendRes.status} ${await sendRes.text()}`);
console.log(`Visitor intelligence email sent to ${recipients.join(', ')}`);
